# Generated by Django 4.2.1 on 2023-06-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='status_type',
            field=models.CharField(choices=[('MODERATOR', 'Moderator'), ('BASE_USER', 'Base_user'), ('CONTENT_MANAGER', 'Content_manager')], default='BASE_USER', max_length=50, verbose_name='роль'),
        ),
    ]
