# Generated by Django 4.2.1 on 2023-05-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.CharField(default='', max_length=100, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_email',
            field=models.EmailField(max_length=100, verbose_name='электронная почта'),
        ),
    ]
