# Generated by Django 4.2.1 on 2023-05-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contacts_message_alter_contacts_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'блог'},
        ),
    ]
