# Generated by Django 4.2.1 on 2023-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='message',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_email',
            field=models.CharField(max_length=100, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(verbose_name='дата последнего изменения'),
        ),
    ]
