# Generated by Django 4.2.1 on 2023-06-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_blog_remove_contacts_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
