# Generated by Django 4.2.1 on 2023-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('post', models.CharField(max_length=100, verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='изображение')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('likes', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('total_views', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
            },
        ),
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.CharField(default='', max_length=100, verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_email',
            field=models.EmailField(max_length=100, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения'),
        ),
    ]
