# Generated by Django 4.2.1 on 2023-06-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.product'),
        ),
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
